name: CI
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  schedule:
    - cron: '0 20 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
    
     #debug workflow
     # - name: Setup tmate session
     #   uses: mxschmitt/action-tmate@v3
     #   timeout-minutes: 150
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          chmod +x custom_theme.sh && ./custom_theme.sh
          chmod +x deploy.sh && ./deploy.sh
