name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
    

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls -an  .
          whoami
          python --version
          find /opt/az/lib/python3.6/site-packages/  -name 'mkdocs' -type d 
          tree /opt/az/lib/python3.6/site-packages/mkdocs
          # chmod +x custom_theme.sh && ./custom_theme.sh
          # chmod +x deploy.sh && ./deploy.sh
